### ISSUE TITLE
TypeError: 'int' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by sotsugov** [JuanPotato/Legofy#25]
Cannot get it to run, because of 
TypeError
```
$ python legofy/cli.py nexmo.png
Static image detected, will now legofy and save as /lego_nexmo.png
Traceback (most recent call last):
  File "legofy/cli.py", line 17, in <module>
    main()
  File "/Library/Python/2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "legofy/cli.py", line 14, in main
    legofy.main(image, brick=brick)
  File "/Library/Python/2.7/site-packages/legofy-0.0.1-py2.7.egg/legofy/__init__.py", line 131, in main
    makeLegoImage(baseImage, brick).save(newFilename)
  File "/Library/Python/2.7/site-packages/legofy-0.0.1-py2.7.egg/legofy/__init__.py", line 67, in makeLegoImage
    legoImage.paste(makeLegoBrick(brick, bp[0], bp[1], bp[2]), (x * width, y * height, (x + 1) * width, (y + 1) * height))
TypeError: 'int' object has no attribute '__getitem__'
```

**Comment by sotsugov** [comment]
Seem to be the problem with handling PNG type images. JPG works fine.

**Comment by JuanPotato** [comment]
No idea if this is fixed, please try with the newest code.

**Comment by sotsugov** [comment]
Seems better with update, thanks.
