### ISSUE TITLE
UnicodeEncodeError on file param

### ISSUE THREAD

**Issue by josx** [JuanPotato/Legofy#30]
Run:
```bash 
$ legofy /home/xxx/Imágenes/4.jpg
```

Get Error:
```
Traceback (most recent call last):
  File "/usr/local/bin/legofy", line 9, in <module>
    load_entry_point('legofy==0.0.1', 'console_scripts', 'legofy')()
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/legofy-0.0.1-py2.7.egg/legofy/cli.py", line 16, in main
    legofy.main(image, brick=brick)
  File "/usr/local/lib/python2.7/dist-packages/legofy-0.0.1-py2.7.egg/legofy/__init__.py", line 84, in main
    newFilename = '{0}/lego_{1}'.format(*os.path.split(filename))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 13: ordinal not in range(128)
```

**Comment by JuanPotato** [comment]
This should be fixed, please try with the newest code.
