### ISSUE TITLE
Legofy animated gif results in OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by davidpkatz** [JuanPotato/Legofy#39]
`15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64`
```
Animated gif detected, will now legofy each frame and recreate the gif and save as lego_pixel_waterfall_bg__by_isohei-d4xntof.gif
Working on frame_0000.png
Working on frame_0001.png
Working on frame_0002.png
Working on frame_0003.png
Working on frame_0004.png
Working on frame_0005.png
Working on frame_0006.png
Working on frame_0007.png
convert -delay 10 -loop 0 ./tmp_frames/*.png /lego_pixel_waterfall_bg__by_isohei-d4xntof.gif
Traceback (most recent call last):
  File "/usr/local/bin/legofy", line 9, in <module>
    load_entry_point('legofy==0.0.1', 'console_scripts', 'legofy')()
  File "/Library/Python/2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/legofy-0.0.1-py2.7.egg/legofy/cli.py", line 14, in main
    legofy.main(image, brick=brick)
  File "/Library/Python/2.7/site-packages/legofy-0.0.1-py2.7.egg/legofy/__init__.py", line 119, in main
    call(command.split(" "))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by JuanPotato** [comment]
This should be fixed, please try with the newest code.
