### ISSUE TITLE
Error legofying a gif

### ISSUE THREAD

**Issue by k1lly** [JuanPotato/Legofy#56]
![screen shot 2015-11-02 at 6 24 33 am](https://cloud.githubusercontent.com/assets/2467931/10873763/692049d6-812a-11e5-9bb6-401cf1804b31.png)
_Text:_
`Working on frame_0328.png
Working on frame_0329.png
Working on frame_0330.png
Working on frame_0331.png
convert -delay 4 -loop 0 ./tmp_frames/*.png /Users/k1lly/Pictures/lego_1.gif
Traceback (most recent call last):
  File "/usr/local/bin/legofy", line 9, in <module>
    load_entry_point('legofy==0.0.1', 'console_scripts', 'legofy')()
  File "/Library/Python/2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/legofy-0.0.1-py2.7.egg/legofy/cli.py", line 13, in main
    legofy.main(image)
  File "/Library/Python/2.7/site-packages/legofy-0.0.1-py2.7.egg/legofy/__init__.py", line 133, in main
    call(command.split(" "))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
server:Pictures k1lly$ 
`

**Comment by JuanPotato** [comment]
Are you using the latest version? What was the command you typed and in what directory?

**Comment by k1lly** [comment]
Yes I'm using the latest version, just git cloned it to my mac, pythohn 2.7.10
`server:Pictures k1lly$ legofy 1.gif
Animated gif detected, will now legofy each frame and recreate the gif and save as lego_1.gif
Working on frame_0000.png`
![screen shot 2015-11-02 at 6 30 29 am](https://cloud.githubusercontent.com/assets/2467931/10873826/452b0146-812b-11e5-819c-9eb046d667fb.png)

**Comment by k1lly** [comment]
Thats it, ive installed imagemagic and it worked after changing the __init__.py file Line: 133
to
call(command, shell=True)
