### ISSUE TITLE
Error converting non-animated gif

### ISSUE THREAD

**Issue by JIghtuse** [JuanPotato/Legofy#59]
I tried to convert this gif from libtiff package:

https://drive.google.com/file/d/0B-4dcK3QuA_LQzc2S3cxcEZYTUE/view?usp=sharing

and got this stacktrace:

    $ legofy  ring.gif out.gif
    Static image detected, will now legofy to /home/jightuse/code/projects/Legofy/out.png
    Traceback (most recent call last):
      File "/home/jightuse//.local/bin/legofy", line 9, in <module>
        load_entry_point('legofy==0.0.1', 'console_scripts', 'legofy')()
      File "/home/jightuse/.local/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 700, in __call__
        return self.main(*args, **kwargs)
      File "/home/jightuse/.local/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 680, in main
        rv = self.invoke(ctx)
      File "/home/jightuse/.local/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 873, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/jightuse/.local/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 508, in invoke
        return callback(*args, **kwargs)
      File "/home/jightuse/.local/lib/python2.7/site-packages/legofy-0.0.1-py2.7.egg/legofy/cli.py", line 19, in main
        legofy.main(image, output=output)
      File "/home/jightuse/.local/lib/python2.7/site-packages/legofy-0.0.1-py2.7.egg/legofy/__init__.py", line 189, in main
        legofy_image(base_image, brick_image, output_path)
      File "/home/jightuse/.local/lib/python2.7/site-packages/legofy-0.0.1-py2.7.egg/legofy/__init__.py", line 149, in legofy_image
        make_lego_image(base_image, brick_image).save(output_path)
      File "/home/jightuse/.local/lib/python2.7/site-packages/legofy-0.0.1-py2.7.egg/legofy/__init__.py", line 58, in make_lego_image
        lego_image.paste(make_lego_brick(brick_image, bp[0], bp[1], bp[2]), (x * brick_width, y * brick_height, (x + 1) * brick_width, (y + 1) * brick_height))
    TypeError: 'int' object has no attribute '__getitem__'

**Comment by JuanPotato** [comment]
I think I know the problem, will fix once I get home.
