### ISSUE TITLE
ValueError:

### ISSUE THREAD

**Issue by FrankDraws** [JuanPotato/Legofy#66]
I ran the following: `sudo python setup.py install` and at the end of the program I got this `ValueError: --enable-jpeg requested but jpeg not found, aborting.`

Is there a jpeg missing?

**Comment by Dbroqua** [comment]
Hi,

This error is a missing dependance for the Pillow library.

To fix it, on my Xubuntu I simply install the python-pil package.

**Comment by FrankDraws** [comment]
Forgot to mention I'm on OSX 10.10.5 (Yosemite).

I found this: https://mail.python.org/pipermail/python-list/2015-February/685927.html

Will need to look into it further.

Thanks @Dbroqua

**Comment by JuanPotato** [comment]
@frankdraws You need to install libjpeg for Mac http://ethan.tira-thompson.com/Mac_OS_X_Ports.html

I'll add this in the README soon

**Comment by JuanPotato** [comment]
@FrankDraws you there?

**Comment by nabijaczleweli** [comment]
he ded
liek so ded

**Comment by christoga** [comment]
I think he more likely to view his bitbucket, I see it on his blog (http://frankjuval.com/)
He said his stack is : "Git via Bitbucket"
I think he's prefer to use bitbucket rather than github.

@JuanPotato I think you better see his social media link on his blog.

**Comment by christoga** [comment]
I also get the same bug 😂
```
# root user
$ python setup.py install
running install
Checking .pth file support in /Library/Python/2.7/site-packages/
/usr/bin/python -E -c pass
TEST PASSED: /Library/Python/2.7/site-packages/ appears to support .pth files
running bdist_egg
running egg_info
creating legofy.egg-info
writing requirements to legofy.egg-info/requires.txt
writing legofy.egg-info/PKG-INFO
writing top-level names to legofy.egg-info/top_level.txt
writing dependency_links to legofy.egg-info/dependency_links.txt
writing entry points to legofy.egg-info/entry_points.txt
writing manifest file 'legofy.egg-info/SOURCES.txt'
reading manifest file 'legofy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'legofy.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.11-intel/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/legofy
copying legofy/__init__.py -> build/lib/legofy
copying legofy/cli.py -> build/lib/legofy
creating build/lib/legofy/assets
creating build/lib/legofy/assets/bricks
copying legofy/assets/bricks/1x1.png -> build/lib/legofy/assets/bricks
creating build/bdist.macosx-10.11-intel
creating build/bdist.macosx-10.11-intel/egg
creating build/bdist.macosx-10.11-intel/egg/legofy
copying build/lib/legofy/__init__.py -> build/bdist.macosx-10.11-intel/egg/legofy
creating build/bdist.macosx-10.11-intel/egg/legofy/assets
creating build/bdist.macosx-10.11-intel/egg/legofy/assets/bricks
copying build/lib/legofy/assets/bricks/1x1.png -> build/bdist.macosx-10.11-intel/egg/legofy/assets/bricks
copying build/lib/legofy/cli.py -> build/bdist.macosx-10.11-intel/egg/legofy
byte-compiling build/bdist.macosx-10.11-intel/egg/legofy/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.11-intel/egg/legofy/cli.py to cli.pyc
creating build/bdist.macosx-10.11-intel/egg/EGG-INFO
copying legofy.egg-info/PKG-INFO -> build/bdist.macosx-10.11-intel/egg/EGG-INFO
copying legofy.egg-info/SOURCES.txt -> build/bdist.macosx-10.11-intel/egg/EGG-INFO
copying legofy.egg-info/dependency_links.txt -> build/bdist.macosx-10.11-intel/egg/EGG-INFO
copying legofy.egg-info/entry_points.txt -> build/bdist.macosx-10.11-intel/egg/EGG-INFO
copying legofy.egg-info/requires.txt -> build/bdist.macosx-10.11-intel/egg/EGG-INFO
copying legofy.egg-info/top_level.txt -> build/bdist.macosx-10.11-intel/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
legofy.__init__: module references __file__
creating dist
creating 'dist/legofy-0.0.1-py2.7.egg' and adding 'build/bdist.macosx-10.11-intel/egg' to it
removing 'build/bdist.macosx-10.11-intel/egg' (and everything under it)
Processing legofy-0.0.1-py2.7.egg
creating /Library/Python/2.7/site-packages/legofy-0.0.1-py2.7.egg
Extracting legofy-0.0.1-py2.7.egg to /Library/Python/2.7/site-packages
Adding legofy 0.0.1 to easy-install.pth file
Installing legofy script to /usr/local/bin

Installed /Library/Python/2.7/site-packages/legofy-0.0.1-py2.7.egg
Processing dependencies for legofy==0.0.1
Searching for click
Reading https://pypi.python.org/simple/click/
Best match: click 5.1
Downloading https://pypi.python.org/packages/source/c/click/click-5.1.tar.gz#md5=9c5323008cccfe232a8b161fc8196d41
Processing click-5.1.tar.gz
Writing /tmp/easy_install-1M5Zqt/click-5.1/setup.cfg
Running click-5.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-1M5Zqt/click-5.1/egg-dist-tmp-6urEjw
warning: no previously-included files matching '*.pyc' found under directory 'docs'
warning: no previously-included files matching '*.pyo' found under directory 'docs'
warning: no previously-included files matching '*.pyc' found under directory 'tests'
warning: no previously-included files matching '*.pyo' found under directory 'tests'
warning: no previously-included files matching '*.pyc' found under directory 'examples'
warning: no previously-included files matching '*.pyo' found under directory 'examples'
no previously-included directories found matching 'docs/_build'
zip_safe flag not set; analyzing archive contents...
click.core: module references __file__
Adding click 5.1 to easy-install.pth file

Installed /Library/Python/2.7/site-packages/click-5.1-py2.7.egg
Searching for pillow
Reading https://pypi.python.org/simple/pillow/
Best match: Pillow 3.0.0
Downloading https://pypi.python.org/packages/source/P/Pillow/Pillow-3.0.0.zip#md5=dd81f6cc3f3a5e5fe72f0f1d936339c3
Processing Pillow-3.0.0.zip
Writing /tmp/easy_install-FnHetR/Pillow-3.0.0/setup.cfg
Running Pillow-3.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-FnHetR/Pillow-3.0.0/egg-dist-tmp-amSMIy
Traceback (most recent call last):
  File "setup.py", line 27, in <module>
    tests_require=['nose'],
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/install.py", line 101, in do_egg_install
    cmd.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 374, in run
    self.easy_install(spec, not self.no_deps)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 590, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 641, in install_item
    self.process_distribution(spec, dist, deps)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 687, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 568, in resolve
    dist = best[req.key] = env.best_match(req, self, installer)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 806, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 818, in obtain
    return installer(requirement)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 609, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 639, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 825, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 1031, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 1016, in run_setup
    run_setup(setup_script, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 69, in run_setup
    lambda: execfile(
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 120, in run
    return func()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 71, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 767, in <module>
    
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/bdist_egg.py", line 185, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/bdist_egg.py", line 171, in call_command
    self.run_command(cmdname)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/install_lib.py", line 20, in run
    self.build()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_ext.py", line 337, in run
    self.build_extensions()
  File "setup.py", line 515, in build_extensions
    
ValueError: --enable-jpeg requested but jpeg not found, aborting.
```
I try to install libjpeg but I can't add it because it's from unindentified developer 😕

**Comment by JuanPotato** [comment]
@christoga try installing [macports](https://www.macports.org/install.php) then do `sudo port install libjpeg-turbo`

or you can use [homebrew](http://brew.sh/) `brew install libjpeg`

remember to uninstall Pillow from pip `pip uninstall pillow` installl libjpeg, then install pillow `pip install pillow`

**Comment by FrankDraws** [comment]
Ha! I'm here. Sorry. I'm slammed at work.

I can't remember where I left off on this. Will have to look into it tomorrow. I'm headed out. {{drops mouse}}

**Comment by JuanPotato** [comment]
added pillow docs to readme
